export const RESULT_MAP: Record<string, string> = {
  aaaa: '겉바속촉 재계 서열 1위 모범생',
  aaab: '겉바속촉 재계 서열 1위 불량아',
  aaba: '겉바속촉 소시민 모범생',
  aabb: '겉바속촉 소시민 불량아',
  abaa: '겉촉속촉 재계 서열 1위 모범생',
  abab: '겉촉속촉 재계 서열 1위 불량아',
  abba: '겉촉속촉 소시민 모범생',
  abbb: '겉촉속촉 소시민 불량아',
  baaa: '겉바속바 재계 서열 1위 모범생',
  baab: '겉바속바 재계 서열 1위 불량아',
  baba: '겉바속바 소시민 모범생',
  babb: '겉바속바 소시민 불량아',
  bbaa: '겉촉속바 재계 서열 1위 모범생',
  bbab: '겉촉속바 재계 서열 1위 불량아',
  bbba: '겉촉속바 소시민 모범생',
  bbbb: '겉촉속바 소시민 불량아',
};

export const RESULT_COMPATIBILITY_MAP: Record<
  string,
  { good: string; bad: string }
> = {
  aaaa: { good: 'abbb', bad: 'bbaa' },
  aaab: { good: 'aabb', bad: 'bbaa' },
  aaba: { good: 'abba', bad: 'bbba' },
  aabb: { good: 'aaab', bad: 'bbaa' },
  abaa: { good: 'bbbb', bad: 'baab' },
  abab: { good: 'aabb', bad: 'bbaa' },
  abba: { good: 'aaba', bad: 'bbab' },
  abbb: { good: 'aaaa', bad: 'bbaa' },
  baaa: { good: 'aaaa', bad: 'bbab' },
  baab: { good: 'aaab', bad: 'abab' },
  baba: { good: 'abba', bad: 'bbba' },
  babb: { good: 'aabb', bad: 'abbb' },
  bbaa: { good: 'aaaa', bad: 'aabb' },
  bbab: { good: 'aaab', bad: 'baaa' },
  bbba: { good: 'abba', bad: 'aaba' },
  bbbb: { good: 'abbb', bad: 'abab' },
};
