# Generated by Django 5.2.4 on 2025-07-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('choice1', models.CharField(blank=True, max_length=1, null=True)),
                ('choice2', models.CharField(blank=True, max_length=1, null=True)),
                ('choice3', models.CharField(blank=True, max_length=1, null=True)),
                ('choice4', models.CharField(blank=True, max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
