# Generated by Django 5.2.4 on 2025-07-31 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_participant_delete_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='choice1',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='choice2',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='choice3',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='choice4',
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_num', models.IntegerField()),
                ('choice', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.participant')),
            ],
        ),
    ]
